# Generated by Django 5.2.1 on 2025-05-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product/%Y/%m/%d"),
        ),
    ]
