# Generated by Django 5.2.1 on 2025-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="stoke",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
