# Generated by Django 5.2.1 on 2025-05-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_available_product_stoke"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="paid",
        ),
    ]
